api:
  build: .
  ports:
    - "4000:3000"
  environment:
    - VIRTUAL_HOST=api.whatsvote.leonadi.de
    - LETSENCRYPT_HOST=api.whatsvote.leonadi.de
    - LETSENCRYPT_EMAIL=leon@leonadi.de
  restart: always
  links:
    - db
    - mqtt

db:
  image: rethinkdb
  restart: always
  volumes:
    - "/opt:/data"

mqtt:
  image: ansi/mosquitto
  restart: always

whatsapp:
  build: ../axiom
  restart: always
  links:
    - mqtt

frontend:
  build: ../whatsvote-app
  ports:
    - "8080:80"
  environment:
    - VIRTUAL_HOST=whatsvote.leonadi.de
    - LETSENCRYPT_HOST=whatsvote.leonadi.de
    - LETSENCRYPT_EMAIL=bot@whatsvote.leonadi.de
  restart: always
